version: 0.2

phases:
  pre_build:
    commands:
      - pwd
      - ls -al
      - terraform init
  build:
    commands:
      - terraform plan
  post_build:
    commands:
      - terraform apply --auto-approve