version: 0.2

phases:
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform plan
  post_build:
    commands:
      - echo Build completed on `date`
      - imagedefinitions.json
artifacts:
  files: imagedefinitions.json